@startuml

Container --> main.py : start
main.py --> service.run
service.run --> rest_handler.setup : pass in operations
service.run --> graphql_handler.setup : pass in operations
service.run --> service.loader.load : load vocab
service.run --> Container : ready
@enduml